const TEMP_USERS = [
  {
    id: 1,
    firstName: "Rick",
    lastName: "Sanchez",
    email: "wubbalubbadubdub@gmail.com",
    balance: 1000,
  },
  {
    id: 2,
    firstName: "Morty",
    lastName: "Smith",
    email: "morty@morty.com",
    balance: 500,
  },
  {
    id: 3,
    firstName: "Summer",
    lastName: "Smith",
    email: "summer@summer.com",
    balance: 200,
  },
  {
    id: 4,
    firstName: "Jerry",
    lastName: "Smith",
    email: "jerry@jerry.com",
    balance: 100,
  },
  {
    id: 5,
    firstName: "Beth",
    lastName: "Smith",
    email: "beth@beth.com",
    balance: 500,
  },
  {
    id: 6,
    firstName: "Mr.",
    lastName: "Poopybutthole",
    email: "poopybutthole@gmail.com",
    balance: 1000,
  },
  {
    id: 7,
    firstName: "Birdperson",
    lastName: "Birdsworth",
    email: "birdperson@birdperson.com",
    balance: 500,
  },
  {
    id: 8,
    firstName: "Squanchy",
    lastName: "Squancherson",
    email: "squanchy@squanchy.com",
    balance: 200,
  },
  {
    id: 9,
    firstName: "Pickle Rick",
    lastName: "Sanchez",
    email: "picklerick@gmail.com",
    balance: 1000,
  },
  {
    id: 10,
    firstName: "Evil Morty",
    lastName: "Smith",
    email: "evilmorty@evilmorty.com",
    balance: 500,
  },
  {
    id: 11,
    firstName: "Rick Prime",
    lastName: "Sanchez",
    email: "rickprime@gmail.com",
    balance: 1000,
  },
  {
    id: 12,
    firstName: "Morticia",
    lastName: "Smith",
    email: "morticia@morticia.com",
    balance: 200,
  },
  {
    id: 13,
    firstName: "Zeep",
    lastName: "Xanflorp",
    email: "zeep@zeep.com",
    balance: 500,
  },
  {
    id: 14,
    firstName: "Krombopulos Michael",
    lastName: "Krombopulos",
    email: "krombopulos@krombopulos.com",
    balance: 1000,
  },
  {
    id: 15,
    firstName: "Scary Terry",
    lastName: "Terryson",
    email: "scaryterry@scaryterry.com",
    balance: 500,
  },
  {
    id: 16,
    firstName: "Mr. Meeseeks",
    lastName: "Meeseeks",
    email: "mrmeeseeks@mrmeeseeks.com",
    balance: 200,
  },
  {
    id: 17,
    firstName: "Tammy",
    lastName: "Guetermann",
    email: "tammy@tammy.com",
    balance: 500,
  },
  {
    id: 18,
    firstName: "Jessica",
    lastName: "Jessicason",
    email: "jessica@jessica.com",
    balance: 200,
  },
  {
    id: 19,
    firstName: "Brad",
    lastName: "Bradson",
    email: "brad@brad.com",
    balance: 100,
  },
  {
    id: 20,
    firstName: "Nathan",
    lastName: "Nathanson",
    email: "nathan@nathan.com",
    balance: 500,
  },
];

export default TEMP_USERS;
